# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindowhaByxU.ui'
##
## Created by: Qt User Interface Compiler version 6.7.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QDateTimeEdit,
    QDoubleSpinBox, QGroupBox, QLabel, QLineEdit,
    QListWidget, QListWidgetItem, QMainWindow, QPushButton,
    QSizePolicy, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(640, 480)
        icon = QIcon()
        icon.addFile(u"cnrdiff-logo.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.groupBoxInput = QGroupBox(self.centralwidget)
        self.groupBoxInput.setObjectName(u"groupBoxInput")
        self.groupBoxInput.setGeometry(QRect(20, 10, 601, 321))
        self.labelInputFileType = QLabel(self.groupBoxInput)
        self.labelInputFileType.setObjectName(u"labelInputFileType")
        self.labelInputFileType.setGeometry(QRect(20, 190, 91, 31))
        self.comboBoxInputFileType = QComboBox(self.groupBoxInput)
        self.comboBoxInputFileType.addItem("")
        self.comboBoxInputFileType.addItem("")
        self.comboBoxInputFileType.setObjectName(u"comboBoxInputFileType")
        self.comboBoxInputFileType.setGeometry(QRect(110, 190, 131, 31))
        self.labelHow = QLabel(self.groupBoxInput)
        self.labelHow.setObjectName(u"labelHow")
        self.labelHow.setGeometry(QRect(260, 190, 31, 31))
        self.comboBoxHow = QComboBox(self.groupBoxInput)
        self.comboBoxHow.addItem("")
        self.comboBoxHow.addItem("")
        self.comboBoxHow.setObjectName(u"comboBoxHow")
        self.comboBoxHow.setGeometry(QRect(290, 190, 81, 31))
        self.pushButtonAddFile = QPushButton(self.groupBoxInput)
        self.pushButtonAddFile.setObjectName(u"pushButtonAddFile")
        self.pushButtonAddFile.setGeometry(QRect(510, 190, 31, 31))
        self.pushButtonRemoveFile = QPushButton(self.groupBoxInput)
        self.pushButtonRemoveFile.setObjectName(u"pushButtonRemoveFile")
        self.pushButtonRemoveFile.setGeometry(QRect(550, 190, 31, 31))
        self.comboBoxBy = QComboBox(self.groupBoxInput)
        self.comboBoxBy.addItem("")
        self.comboBoxBy.addItem("")
        self.comboBoxBy.setObjectName(u"comboBoxBy")
        self.comboBoxBy.setGeometry(QRect(410, 190, 81, 31))
        self.labelBy = QLabel(self.groupBoxInput)
        self.labelBy.setObjectName(u"labelBy")
        self.labelBy.setGeometry(QRect(390, 190, 21, 31))
        self.doubleSpinBoxElevationCutoff = QDoubleSpinBox(self.groupBoxInput)
        self.doubleSpinBoxElevationCutoff.setObjectName(u"doubleSpinBoxElevationCutoff")
        self.doubleSpinBoxElevationCutoff.setEnabled(False)
        self.doubleSpinBoxElevationCutoff.setGeometry(QRect(470, 270, 111, 31))
        self.doubleSpinBoxElevationCutoff.setDecimals(3)
        self.doubleSpinBoxElevationCutoff.setMaximum(90.000000000000000)
        self.doubleSpinBoxElevationCutoff.setSingleStep(10.000000000000000)
        self.dateTimeEditStartTime = QDateTimeEdit(self.groupBoxInput)
        self.dateTimeEditStartTime.setObjectName(u"dateTimeEditStartTime")
        self.dateTimeEditStartTime.setEnabled(False)
        self.dateTimeEditStartTime.setGeometry(QRect(110, 230, 211, 31))
        self.checkBoxStartTime = QCheckBox(self.groupBoxInput)
        self.checkBoxStartTime.setObjectName(u"checkBoxStartTime")
        self.checkBoxStartTime.setGeometry(QRect(20, 230, 81, 31))
        self.checkBoxInterval = QCheckBox(self.groupBoxInput)
        self.checkBoxInterval.setObjectName(u"checkBoxInterval")
        self.checkBoxInterval.setGeometry(QRect(340, 230, 121, 31))
        self.doubleSpinBoxInterval = QDoubleSpinBox(self.groupBoxInput)
        self.doubleSpinBoxInterval.setObjectName(u"doubleSpinBoxInterval")
        self.doubleSpinBoxInterval.setEnabled(False)
        self.doubleSpinBoxInterval.setGeometry(QRect(470, 230, 111, 31))
        self.doubleSpinBoxInterval.setDecimals(3)
        self.doubleSpinBoxInterval.setMinimum(0.010000000000000)
        self.doubleSpinBoxInterval.setMaximum(60.000000000000000)
        self.doubleSpinBoxInterval.setSingleStep(0.010000000000000)
        self.doubleSpinBoxInterval.setValue(1.000000000000000)
        self.dateTimeEditEndTime = QDateTimeEdit(self.groupBoxInput)
        self.dateTimeEditEndTime.setObjectName(u"dateTimeEditEndTime")
        self.dateTimeEditEndTime.setEnabled(False)
        self.dateTimeEditEndTime.setGeometry(QRect(110, 270, 211, 31))
        self.checkBoxElevationCutoff = QCheckBox(self.groupBoxInput)
        self.checkBoxElevationCutoff.setObjectName(u"checkBoxElevationCutoff")
        self.checkBoxElevationCutoff.setEnabled(False)
        self.checkBoxElevationCutoff.setGeometry(QRect(340, 270, 121, 31))
        self.checkBoxEndTime = QCheckBox(self.groupBoxInput)
        self.checkBoxEndTime.setObjectName(u"checkBoxEndTime")
        self.checkBoxEndTime.setGeometry(QRect(20, 270, 81, 31))
        self.listWidgetInput = QListWidget(self.groupBoxInput)
        self.listWidgetInput.setObjectName(u"listWidgetInput")
        self.listWidgetInput.setGeometry(QRect(20, 30, 561, 151))
        self.groupBoxOutput = QGroupBox(self.centralwidget)
        self.groupBoxOutput.setObjectName(u"groupBoxOutput")
        self.groupBoxOutput.setGeometry(QRect(20, 340, 601, 121))
        self.checkBoxExportCNR = QCheckBox(self.groupBoxOutput)
        self.checkBoxExportCNR.setObjectName(u"checkBoxExportCNR")
        self.checkBoxExportCNR.setGeometry(QRect(20, 30, 101, 31))
        self.checkBoxPlotDCNR = QCheckBox(self.groupBoxOutput)
        self.checkBoxPlotDCNR.setObjectName(u"checkBoxPlotDCNR")
        self.checkBoxPlotDCNR.setGeometry(QRect(260, 30, 101, 31))
        self.checkBoxExportDCNR = QCheckBox(self.groupBoxOutput)
        self.checkBoxExportDCNR.setObjectName(u"checkBoxExportDCNR")
        self.checkBoxExportDCNR.setGeometry(QRect(140, 30, 101, 31))
        self.checkBoxExportXLSX = QCheckBox(self.groupBoxOutput)
        self.checkBoxExportXLSX.setObjectName(u"checkBoxExportXLSX")
        self.checkBoxExportXLSX.setGeometry(QRect(380, 30, 101, 31))
        self.labelOutputDirectory = QLabel(self.groupBoxOutput)
        self.labelOutputDirectory.setObjectName(u"labelOutputDirectory")
        self.labelOutputDirectory.setGeometry(QRect(20, 70, 101, 31))
        self.lineEditOutputDirectory = QLineEdit(self.groupBoxOutput)
        self.lineEditOutputDirectory.setObjectName(u"lineEditOutputDirectory")
        self.lineEditOutputDirectory.setEnabled(False)
        self.lineEditOutputDirectory.setGeometry(QRect(130, 70, 351, 31))
        self.pushButtonSelect = QPushButton(self.groupBoxOutput)
        self.pushButtonSelect.setObjectName(u"pushButtonSelect")
        self.pushButtonSelect.setEnabled(False)
        self.pushButtonSelect.setGeometry(QRect(500, 70, 81, 31))
        self.pushButtonProcess = QPushButton(self.groupBoxOutput)
        self.pushButtonProcess.setObjectName(u"pushButtonProcess")
        self.pushButtonProcess.setEnabled(False)
        self.pushButtonProcess.setGeometry(QRect(500, 30, 81, 31))
        MainWindow.setCentralWidget(self.centralwidget)
        QWidget.setTabOrder(self.listWidgetInput, self.comboBoxInputFileType)
        QWidget.setTabOrder(self.comboBoxInputFileType, self.comboBoxHow)
        QWidget.setTabOrder(self.comboBoxHow, self.comboBoxBy)
        QWidget.setTabOrder(self.comboBoxBy, self.pushButtonAddFile)
        QWidget.setTabOrder(self.pushButtonAddFile, self.pushButtonRemoveFile)
        QWidget.setTabOrder(self.pushButtonRemoveFile, self.checkBoxStartTime)
        QWidget.setTabOrder(self.checkBoxStartTime, self.dateTimeEditStartTime)
        QWidget.setTabOrder(self.dateTimeEditStartTime, self.checkBoxEndTime)
        QWidget.setTabOrder(self.checkBoxEndTime, self.dateTimeEditEndTime)
        QWidget.setTabOrder(self.dateTimeEditEndTime, self.checkBoxInterval)
        QWidget.setTabOrder(self.checkBoxInterval, self.doubleSpinBoxInterval)
        QWidget.setTabOrder(self.doubleSpinBoxInterval, self.checkBoxElevationCutoff)
        QWidget.setTabOrder(self.checkBoxElevationCutoff, self.doubleSpinBoxElevationCutoff)
        QWidget.setTabOrder(self.doubleSpinBoxElevationCutoff, self.checkBoxExportCNR)
        QWidget.setTabOrder(self.checkBoxExportCNR, self.checkBoxExportDCNR)
        QWidget.setTabOrder(self.checkBoxExportDCNR, self.checkBoxPlotDCNR)
        QWidget.setTabOrder(self.checkBoxPlotDCNR, self.checkBoxExportXLSX)
        QWidget.setTabOrder(self.checkBoxExportXLSX, self.lineEditOutputDirectory)
        QWidget.setTabOrder(self.lineEditOutputDirectory, self.pushButtonSelect)
        QWidget.setTabOrder(self.pushButtonSelect, self.pushButtonProcess)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"CNRDIFF", None))
        self.groupBoxInput.setTitle(QCoreApplication.translate("MainWindow", u"Input", None))
        self.labelInputFileType.setText(QCoreApplication.translate("MainWindow", u"Input File Type", None))
        self.comboBoxInputFileType.setItemText(0, QCoreApplication.translate("MainWindow", u"RINEX V3 OBS", None))
        self.comboBoxInputFileType.setItemText(1, QCoreApplication.translate("MainWindow", u"BNC QC LOG", None))

        self.labelHow.setText(QCoreApplication.translate("MainWindow", u"How", None))
        self.comboBoxHow.setItemText(0, QCoreApplication.translate("MainWindow", u"MEAN", None))
        self.comboBoxHow.setItemText(1, QCoreApplication.translate("MainWindow", u"MAX", None))

        self.pushButtonAddFile.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.pushButtonRemoveFile.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.comboBoxBy.setItemText(0, QCoreApplication.translate("MainWindow", u"SYS", None))
        self.comboBoxBy.setItemText(1, QCoreApplication.translate("MainWindow", u"PRN", None))

        self.labelBy.setText(QCoreApplication.translate("MainWindow", u"By", None))
        self.dateTimeEditStartTime.setDisplayFormat(QCoreApplication.translate("MainWindow", u"yyyy-MM-dd HH:mm:ss.zzz", None))
        self.checkBoxStartTime.setText(QCoreApplication.translate("MainWindow", u"Start Time", None))
        self.checkBoxInterval.setText(QCoreApplication.translate("MainWindow", u"Interval", None))
        self.dateTimeEditEndTime.setDisplayFormat(QCoreApplication.translate("MainWindow", u"yyyy-MM-dd HH:mm:ss.zzz", None))
        self.checkBoxElevationCutoff.setText(QCoreApplication.translate("MainWindow", u"Elevation Cut-off", None))
        self.checkBoxEndTime.setText(QCoreApplication.translate("MainWindow", u"End Time", None))
        self.groupBoxOutput.setTitle(QCoreApplication.translate("MainWindow", u"Output", None))
        self.checkBoxExportCNR.setText(QCoreApplication.translate("MainWindow", u"Export CNR", None))
        self.checkBoxPlotDCNR.setText(QCoreApplication.translate("MainWindow", u"Plot DCNR", None))
        self.checkBoxExportDCNR.setText(QCoreApplication.translate("MainWindow", u"Export DCNR", None))
        self.checkBoxExportXLSX.setText(QCoreApplication.translate("MainWindow", u"Export XLSX", None))
        self.labelOutputDirectory.setText(QCoreApplication.translate("MainWindow", u"Output Directory", None))
        self.pushButtonSelect.setText(QCoreApplication.translate("MainWindow", u"Select", None))
        self.pushButtonProcess.setText(QCoreApplication.translate("MainWindow", u"Process", None))
    # retranslateUi

